[package]
name = "hellorust"
version = "0.4.0"
authors = ["niels <place@holder.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = "0.5.13"
specs = "0.15.0"
specs-derive = "0.4.0"
